#!/usr/bin/env python3
"""Google Play listing texts, from store/google-play/listing/listings.json.

    python scripts/play_listing.py

Writes, next to listings.json:
  <code>.md        one page per language (en-US.md, nl-NL.md, ...), each
                   field in a box that copies in one click on GitHub
  whats-new.txt    the release notes of every language in the form Play
                   Console takes them in one paste:
                   <en-US>...</en-US><nl-NL>...</nl-NL>...

Only the Python standard library is needed.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LISTING_DIR = ROOT / 'store' / 'google-play' / 'listing'
LIMITS = {'title': 30, 'shortDescription': 80, 'fullDescription': 4000,
          'whatsNew': 500}


def _box(text):
    return f'```text\n{text}\n```\n'


def main():
    data = json.loads((LISTING_DIR / 'listings.json').read_text(encoding='utf-8'))
    notes = []
    for code, lang in data['languages'].items():
        for field, limit in LIMITS.items():
            if len(lang[field]) > limit:
                raise SystemExit(f'{code} {field}: {len(lang[field])} '
                                 f'characters, Play takes {limit}')
        page = [f"# {lang['language']} ({code})\n",
                'Google Play listing for this language (Play Console → Grow → '
                'Store presence → Main store listing). Generated by '
                '`scripts/play_listing.py` from `listings.json`; edit that '
                'file, not this one.\n',
                '## App name\n', _box(lang['title']),
                '## Short description\n', _box(lang['shortDescription']),
                '## Full description\n', _box(lang['fullDescription']),
                "## Release notes (What's new)\n", _box(lang['whatsNew'])]
        (LISTING_DIR / f'{code}.md').write_text('\n'.join(page), encoding='utf-8')
        notes.append(f'<{code}>\n{lang["whatsNew"]}\n</{code}>')
        print(f'wrote {code}.md')
    (LISTING_DIR / 'whats-new.txt').write_text('\n'.join(notes) + '\n',
                                               encoding='utf-8')
    print('wrote whats-new.txt')


if __name__ == '__main__':
    main()
