#!/usr/bin/env python3
"""Microsoft Store listing texts, from docs/publishing/store-listing/listings.json.

    python scripts/store_listing.py pages
        Writes docs/publishing/store-listing/<language>.md: one page per
        language, each field in a box that copies in one click on GitHub.

    python scripts/store_listing.py fill <exported.csv> [<filled.csv>]
        Fills a listing CSV exported from Partner Center (the app's
        submission > Store listings > Import/export > Export) with the texts
        for every language column it has, and writes it next to it as
        <name>-filled.csv for Import. Rows it has no text for (screenshots,
        trailers, hardware) keep what the export had.

Only the Python standard library is needed.
"""
import csv
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LISTING_DIR = ROOT / 'docs' / 'publishing' / 'store-listing'


def load():
    return json.loads((LISTING_DIR / 'listings.json').read_text(encoding='utf-8'))


def _box(text):
    return f'```text\n{text}\n```\n'


def pages(data):
    common = data['common']
    for code, lang in data['languages'].items():
        out = [f"# {lang['language']} ({code})\n",
               'Microsoft Store listing for this language. Generated by '
               '`scripts/store_listing.py pages` from `listings.json`; '
               'edit that file, not this one.\n',
               '## Product name\n', _box(common['name']),
               '## Short description\n', _box(lang['shortDescription']),
               '## Description\n', _box(lang['description']),
               "## What's new in this version\n", _box(lang['releaseNotes']),
               '## Product features\n']
        for i, feature in enumerate(lang['features'], 1):
            out.append(f'{i}.\n' + _box(feature))
        out.append('## Search terms\n')
        for i, term in enumerate(lang['searchTerms'], 1):
            out.append(f'{i}.\n' + _box(term))
        out += ['## Copyright and trademark info\n', _box(common['copyright']),
                '## Additional license terms\n', _box(common['licenseTerms'])]
        (LISTING_DIR / f'{code}.md').write_text('\n'.join(out), encoding='utf-8')
        print(f'wrote {code}.md')


# The export's first columns are Field, ID, Type and default; every column
# after them is a language. Decided by position: Indonesian's column is "id",
# the ID column's name but for case.
_META_COUNT = 4


def _language_for(header, languages):
    """Our language key for a CSV column header such as "nl-nl"."""
    h = header.strip().lower()
    if h in languages:
        return h
    base = h.split('-')[0]
    if base == 'zh':
        return 'zh-cn' if 'zh-cn' in languages else None
    if base == 'pt':
        return 'pt-br' if 'pt-br' in languages else None
    if base == 'en':
        return 'en-us'
    return base if base in languages else None


def _value_for(field, lang, common):
    """The text for a Partner Center row named [field], or None to keep it."""
    key = re.sub(r'[^a-z0-9]', '', field.lower())
    numbered = re.fullmatch(r'(feature|searchterm|keyword)(\d+)', key)
    if numbered:
        items = lang['features'] if numbered.group(1) == 'feature' else lang['searchTerms']
        index = int(numbered.group(2)) - 1
        return items[index] if 0 <= index < len(items) else ''
    if key == 'description':
        return lang['description']
    if key == 'shortdescription':
        return lang['shortDescription']
    if key in ('releasenotes', 'whatsnew'):
        return lang['releaseNotes']
    if key == 'title':
        return common['name']
    if key.startswith('copyright'):
        return common['copyright']
    if key == 'additionallicenseterms':
        return common['licenseTerms']
    return None


def fill(data, source, target):
    with open(source, encoding='utf-8-sig', newline='') as f:
        rows = list(csv.reader(f))
    if not rows:
        sys.exit(f'{source} is empty')
    header = rows[0]
    languages = data['languages']
    columns = {i: _language_for(h, languages)
               for i, h in enumerate(header) if i >= _META_COUNT}
    used = {i: code for i, code in columns.items() if code}
    if not used:
        sys.exit('No language columns found in the header: ' + ', '.join(header))
    filled = 0
    for row in rows[1:]:
        if not row:
            continue
        for i, code in used.items():
            value = _value_for(row[0], languages[code], data['common'])
            if value is None:
                continue
            while len(row) <= i:
                row.append('')
            row[i] = value
            filled += 1
    with open(target, 'w', encoding='utf-8-sig', newline='') as f:
        csv.writer(f).writerows(rows)
    print(f'{filled} fields filled for {", ".join(sorted(set(used.values())))}')
    missing = sorted(set(languages) - set(used.values()))
    if missing:
        print('Not in the export (add these languages in Partner Center first): '
              + ', '.join(missing))
    print(f'wrote {target}')


def main(argv):
    data = load()
    if len(argv) >= 2 and argv[1] == 'pages':
        pages(data)
    elif len(argv) >= 3 and argv[1] == 'fill':
        source = Path(argv[2])
        target = Path(argv[3]) if len(argv) > 3 else source.with_name(source.stem + '-filled.csv')
        fill(data, source, target)
    else:
        sys.exit(__doc__)


if __name__ == '__main__':
    main(sys.argv)
